name: Build and Deploy to Azure
-build-arg 

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - template: ./build/_build_docker_image.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - template: ./deploy/_deploy_docker_image.yml
