name: Build and Deploy on push on main
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -build-arg BUILD_ID=${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/vue-app:${{ github.sha }}-latest . 

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/vue-app:${{ github.sha }}-latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'TPFinal CP Adrien Verstrepen'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/vue-app:${{ github.sha }}'