name: Build and Deploy to Azure
on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./build/_build_docker_image.yml
    secrets: inherit

  deploy:
    needs: build
    uses: ./deploy/_deploy_docker_image.yml
    secrets: inherit